version: '3.8'

name: ms-name-db

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: gtest # Replace with your desired username
      POSTGRES_PASSWORD: gtest # Replace with your desired password
      POSTGRES_DB: primary-db # Replace with your desired database name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
